apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to the base resources
resources:
- ../../base

# Patches to modify the base deployment
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: dip-forwarder-client