apiVersion: apps/v1
kind: Deployment
metadata:
  name: dip-forwarder-client
  labels:
    app.kubernetes.io/name: dip-forwarder-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dip-forwarder-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dip-forwarder-client
    spec:
      containers:
        - name: dip-forwarder-client
          securityContext:
            {}
          image: ghcr.io/dip-software/dip-wssocks:v0.0.7
          command: ["/app/app", "client", "-addr", ":5432"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          imagePullPolicy: Always
          env:
            - name: WSSOCKS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dip-forwarder-client-token
                  key: token
          ports:
            - name: psql
              containerPort: 5432
              protocol: TCP
            - name: health
              containerPort: 8091
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8091
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8091
            initialDelaySeconds: 15
            periodSeconds: 20